version: "3.8"
services:
  telegram-bot:
    container_name: ${CONTAINER_NAME} 
    build: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN} # Token del bot que escucha
      - TARGET_CHAT_ID=${TARGET_CHAT_ID}
      - FORWARD_MODE=${FORWARD_MODE}
      - TARGET_CHAT_EXCLUSIVO_ID=${TARGET_CHAT_EXCLUSIVO_ID}
      - CHATS_EXCLUIDOS=${CHATS_EXCLUIDOS}
    volumes:
      - ${DOWNLOAD_DIR}:/app/media
    restart: unless-stopped

