version: "3.8"
services:
  telegram-bot:
    build: .
    environment:
      - TELEGRAM_TOKEN="${TELEGRAM_TOKEN}" # Token del bot que escucha
      - TARGET_CHAT_ID="${TARGET_CHAT_ID}"
      - FORWARD_MODE="${FORWARD_MODE}"
    restart: unless-stopped

