version: "3.8"
services:
  telegram-bot:
    container_name: ${CONTAINER_NAME} 
    build: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN} # Token del bot que escucha
      - TARGET_CHAT_ID=${TARGET_CHAT_ID}
      - TARGET_CHAT_ID_ME=${TARGET_CHAT_ID_ME}
      - FORWARD_MODE=${FORWARD_MODE}
      - BARRIDOS=${BARRIDOS}
    volumes:
      - ${DOWNLOAD_DIR}:/app/media
      - ./logs:/app/logs
    restart: unless-stopped

