version: "3.8"
services:
  telegram-bot:
    build: ./bot
    environment:
      - TELEGRAM_TOKEN="${TELEGRAM_TOKEN}" # Token del bot que escucha
      - TARGET_CHAT_ID="${TARGET_CHAT_ID}"
      - FORWARD_MODE="${FORWARD_MODE}"
    volumes:
      - ./messages.json:/app/messages.json
    restart: unless-stopped

